name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-to-PyPi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPi package
        run: ls -al

