name: publish to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      
      - name: poetry config PyPI token
        run: poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}

      - name: Install python libraries
        run: poetry install 

      - name: publish to PyPI
        run: poetry publish --build


      
