name: publish to PyPi

on:
  push:
    branches:
      - "main"

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: echo files list 
        run: ls -al
      - name: python version
        run: python3 --version
        